### ISSUE TITLE
Plugin fails to create configuration .xml file

### ISSUE THREAD

**Issue by leo65** [aviadmini/avi-airdrop#1]
[2/24/2017 7:53:03 AM] [Error] FormatException: The specified format 'X2' is invalid - System.NumberFormatter.NumberToString (System.String format, System.Globalization.NumberFormatInfo nfi)
System.NumberFormatter.NumberToString (System.String format, Single value, IFormatProvider fp)
System.Single.ToString (System.String format, IFormatProvider provider)
System.Single.ToString (System.String format)
aviadmini.rocketmod.AviCommon.Extensions.ToHexColor (Color color)
aviadmini.rocketmod.AirDrop.AirdropPluginConfig.LoadDefaults ()
Rocket.Core.Assets.XMLFileAsset`1[aviadmini.rocketmod.AirDrop.AirdropPluginConfig].Save ()
Rethrow as Exception: Failed to serialize XMLFileAsset: C:/Steam/steamapps/common/Unturned/Servers/BRAINZ7/Rocket/Plugins/AviAirdrop/AviAirdrop.configuration.xml
Rocket.Core.Assets.XMLFileAsset`1[aviadmini.rocketmod.AirDrop.AirdropPluginConfig].Save ()
Rocket.Core.Assets.XMLFileAsset`1[aviadmini.rocketmod.AirDrop.AirdropPluginConfig].Load (Rocket.API.AssetLoaded`1 callback)
Rethrow as Exception: Failed to deserialize XMLFileAsset: C:/Steam/steamapps/common/Unturned/Servers/BRAINZ7/Rocket/Plugins/AviAirdrop/AviAirdrop.configuration.xml
Rocket.Core.Assets.XMLFileAsset`1[aviadmini.rocketmod.AirDrop.AirdropPluginConfig].Load (Rocket.API.AssetLoaded`1 callback)
Rocket.Core.Assets.XMLFileAsset`1[aviadmini.rocketmod.AirDrop.AirdropPluginConfig]..ctor (System.String file, System.Type[] extraTypes, aviadmini.rocketmod.AirDrop.AirdropPluginConfig defaultInstance)
Rocket.Core.Plugins.RocketPlugin`1[RocketPluginConfiguration]..ctor ()
aviadmini.rocketmod.AirDrop.AirdropManager..ctor ()
UnityEngine.GameObject:.ctor(String, Type[])
Rocket.Core.Plugins.RocketPluginManager:loadPlugins()
Rocket.Core.Plugins.RocketPluginManager:Start()

**Comment by aviadmini** [comment]
What color are you trying to use?

**Comment by aviadmini** [comment]
Closed with 27bc3de
