### ISSUE TITLE
What is avi_airdrop.txt?

### ISSUE THREAD

**Issue by Ayria** [aviadmini/avi-airdrop#2]
What is avi_airdrop.txt? I see there is a number string in it, what does it do?

P.S Do you plan to make the drops customizable?

**Comment by aviadmini** [comment]
Currently this file contains time of next airdrop. In next release (which might be not soon) it's handled in a different file. 

I might add random locations in one of next releases.

I'm not really planning to add custom loot (at least not in public release)
